// In diesem File ist eine Liste von 94 Film/Serientiteln gespeichert, welche im script.js eingebunden wird.

export const showTitles = [
    "Under the Dome",
    "Person of Interest",
    "Bitten",
    "Arrow",
    "True Detective",
    "The 100",
    "Homeland",
    "Glee",
    "Grimm",
    "The Flash",
    "Gotham",
    "The Walking Dead",
    "The Big Bang Theory",
    "Marvel's Agents of S.H.I.E.L.D.",
    "The Vampire Diaries",
    "Supernatural",
    "Pretty Little Liars",
    "Grey's Anatomy",
    "The Blacklist",
    "Modern Family",
    "Scandal",
    "Criminal Minds",
    "Once Upon a Time",
    "Bones",
    "The Originals",
    "Castle",
    "Revenge",
    "NCIS",
    "How to Get Away with Murder",
    "The Good Wife",
    "Chicago Fire",
    "The Mentalist",
    "Elementary",
    "The Simpsons",
    "Brooklyn Nine-Nine",
    "The Middle",
    "2 Broke Girls",
    "Mom",
    "New Girl",
    "The Goldbergs",
    "The Mindy Project",
    "Reign",
    "The Tomorrow People",
    "The Carrie Diaries",
    "Hart of Dixie",
    "Beauty and the Beast",
    "Agents of S.H.I.E.L.D.",
    "Constantine",
    "Z Nation",
    "American Horror Story",
    "Sleepy Hollow",
    "Hannibal",
    "Bates Motel",
    "The Following",
    "The Strain",
    "Penny Dreadful",
    "True Blood",
    "The Leftovers",
    "The Knick",
    "Boardwalk Empire",
    "Game of Thrones",
    "The Newsroom",
    "Girls",
    "Veep",
    "Silicon Valley",
    "Orange Is the New Black",
    "Hemlock Grove",
    "Marco Polo",
    "Daredevil",
    "Jessica Jones",
    "Luke Cage",
    "Iron Fist",
    "The Defenders",
    "The Punisher",
    "Stranger Things",
    "13 Reasons Why",
    "The Crown",
    "Black Mirror",
    "Narcos",
    "Mindhunter",
    "Ozark",
    "The Umbrella Academy",
    "The Witcher",
    "Dark",
    "Elite",
    "La Casa de Papel",
    "Sex Education",
    "The End of the F***ing World",
    "You",
    "The Haunting of Hill House",
    "The Haunting of Bly Manor",
    "Locke & Key",
    "Shadow and Bone",
    "Sweet Tooth",
    "Lupin"
  ];